from app.models.action import ActionType

ACTION_DEFINITIONS = {
    ActionType.MOVE: {"requires_target": False, "requires_location": True, "energy_cost": 0.05, "hunger_cost": 0.02, "duration_ticks": 1, "description": "Move to a new location"},
    ActionType.TALK: {"requires_target": True, "requires_location": False, "energy_cost": 0.02, "hunger_cost": 0.01, "duration_ticks": 1, "description": "Talk to someone"},
    ActionType.WORK: {"requires_target": False, "requires_location": False, "energy_cost": 0.1, "hunger_cost": 0.05, "duration_ticks": 4, "description": "Work on a task"},
    ActionType.EAT: {"requires_target": False, "requires_location": False, "energy_cost": -0.05, "hunger_cost": -0.5, "duration_ticks": 1, "description": "Eat a meal"},
    ActionType.REST: {"requires_target": False, "requires_location": False, "energy_cost": -0.2, "hunger_cost": 0.01, "duration_ticks": 2, "description": "Rest and recover energy"},
    ActionType.BUY: {"requires_target": False, "requires_location": False, "energy_cost": 0.01, "hunger_cost": 0.0, "duration_ticks": 1, "description": "Buy an item"},
    ActionType.SELL: {"requires_target": False, "requires_location": False, "energy_cost": 0.01, "hunger_cost": 0.0, "duration_ticks": 1, "description": "Sell an item"},
    ActionType.GIVE: {"requires_target": True, "requires_location": False, "energy_cost": 0.01, "hunger_cost": 0.0, "duration_ticks": 1, "description": "Give an item"},
    ActionType.TAKE: {"requires_target": True, "requires_location": False, "energy_cost": 0.01, "hunger_cost": 0.0, "duration_ticks": 1, "description": "Take an item"},
    ActionType.CALL: {"requires_target": True, "requires_location": False, "energy_cost": 0.01, "hunger_cost": 0.0, "duration_ticks": 1, "description": "Call someone"},
    ActionType.MESSAGE: {"requires_target": True, "requires_location": False, "energy_cost": 0.01, "hunger_cost": 0.0, "duration_ticks": 1, "description": "Send a message"},
    ActionType.MEET: {"requires_target": True, "requires_location": True, "energy_cost": 0.05, "hunger_cost": 0.02, "duration_ticks": 2, "description": "Meet someone"},
    ActionType.ATTEND_EVENT: {"requires_target": False, "requires_location": True, "energy_cost": 0.05, "hunger_cost": 0.02, "duration_ticks": 4, "description": "Attend an event"},
    ActionType.CREATE_EVENT: {"requires_target": False, "requires_location": True, "energy_cost": 0.1, "hunger_cost": 0.02, "duration_ticks": 2, "description": "Create an event"},
    ActionType.QUIT_JOB: {"requires_target": False, "requires_location": False, "energy_cost": 0.05, "hunger_cost": 0.0, "duration_ticks": 1, "description": "Quit job"},
    ActionType.APPLY_FOR_JOB: {"requires_target": False, "requires_location": False, "energy_cost": 0.05, "hunger_cost": 0.0, "duration_ticks": 1, "description": "Apply for job"},
    ActionType.START_PROJECT: {"requires_target": False, "requires_location": False, "energy_cost": 0.1, "hunger_cost": 0.02, "duration_ticks": 2, "description": "Start a project"},
    ActionType.JOIN_GROUP: {"requires_target": False, "requires_location": False, "energy_cost": 0.02, "hunger_cost": 0.0, "duration_ticks": 1, "description": "Join a group"},
    ActionType.LEAVE_GROUP: {"requires_target": False, "requires_location": False, "energy_cost": 0.02, "hunger_cost": 0.0, "duration_ticks": 1, "description": "Leave a group"},
    ActionType.MAKE_FRIEND: {"requires_target": True, "requires_location": False, "energy_cost": 0.05, "hunger_cost": 0.01, "duration_ticks": 2, "description": "Make a friend"},
    ActionType.CONFRONT: {"requires_target": True, "requires_location": False, "energy_cost": 0.1, "hunger_cost": 0.02, "duration_ticks": 2, "description": "Confront someone"},
    ActionType.APOLOGIZE: {"requires_target": True, "requires_location": False, "energy_cost": 0.05, "hunger_cost": 0.01, "duration_ticks": 1, "description": "Apologize"},
    ActionType.HELP: {"requires_target": True, "requires_location": False, "energy_cost": 0.1, "hunger_cost": 0.02, "duration_ticks": 2, "description": "Help someone"},
    ActionType.IGNORE: {"requires_target": True, "requires_location": False, "energy_cost": 0.0, "hunger_cost": 0.0, "duration_ticks": 1, "description": "Ignore someone"},
    ActionType.WAIT: {"requires_target": False, "requires_location": False, "energy_cost": 0.0, "hunger_cost": 0.01, "duration_ticks": 1, "description": "Wait"},
    ActionType.SLEEP: {"requires_target": False, "requires_location": False, "energy_cost": -1.0, "hunger_cost": 0.05, "duration_ticks": 8, "description": "Sleep"},
}
